# This file contains the configuration for the gitlab ci.
#
# To recreate the .gitlab-ci.yml file, run
#   ci-fairy generate-template
#
# The ci-fairy tool is part of
# https://gitlab.freedesktop.org/freedesktop/ci-templates
#

# Some distros are fairly similar, and we reuse similar scripts.
# The base type maps the distro name to their base.
base_types:
  fedora: fedora
  centos: fedora
  debian: debian
  ubuntu: debian
  alpine: alpine

# The list of all distributions we want to create job for.
distributions:
  - name: fedora
    # The first tier:1 in the list is used to build the pages and check-{tree,patch}
    tier: 1
    versions:
      - '39'
  - name: fedora
    tier: 2
    versions:
      - '37'
      - '39'
      - '40'
  - name: fedora
    tier: 3
    versions:
      - '30'
      - '31'
      - '32'
      - '33'
      - '34'
      - '35'
      - '36'
  - name: ubuntu
    tier: 2
    versions:
      - '18.04'
      - '20.04'
      - '22.04'
      - 'devel'
      - 'rolling'
  - name: debian
    tier: 2
    versions:
      - '10'
      - '11'
      - 'sid'
  - name: debian
    tier: 3
    versions:
      - '9'
      - 'testing'
  - name: centos
    tier: 2
    versions:
      - 'stream8'
      - 'stream9'
  - name: alpine
    tier: 2
    versions:
      - 'latest'
